### PR TITLE
Schema updates

### PR DESCRIPTION
**Pull request by Miking98**
C++ needs to be updated

### CODE REVIEW

**Comment by Lalaland** [comment]
Just updated the C++ and everything seems to be working!

/local-scratch/nigam/projects/ethanid/piton_3_extract is my test extract

**Review by rthapa84 — APPROVED** [review]

**Comment by Lalaland** [comment]
This can't be merged until, at minimum, the jax branch is fully merged as it will have a ton of conflicts with jax and I would prefer to resolve the conflicts in this smaller branch rather than the 10k jax branch.

**Comment by Lalaland** [comment]
@Miking98 If you rebase this on the current master branch, we should be able to merge this immediately.

My apologies for the delay!

**Comment by Miking98** [comment]
No worries! Just pulled in the `main` branch,

**Pull request closed without merging**
